### ISSUE TITLE
Setting non-existant cacheFolder crashes Node Red

### ISSUE THREAD

**Issue by ChrisJohns-me** [orcema/node-red-contrib-google-home-notifier-offline#4]
When setting `cacheFolder` to `/config/node-red/GHCache`, the TTS does not play and Node-RED appears to crash and restart.
This only occurs when `cacheFolder` is set, and the specified folder does not exist. After creating the specified folder it works as expected.

### Logs
```
[10/Nov/2019:10:56:21 -0700] 200 10.0.0.221, 172.30.32.1(172.30.32.2) POST /inject/414ac7dd.4e92f8 HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36)
fileServer listening on port 8081
new message -----
10 Nov 10:56:21 - [red] Uncaught Exception:
10 Nov 10:56:21 - Error: ENOENT: no such file or directory, open '/config/node-red/GHCache/TESTING.mp3'
[10/Nov/2019:10:56:21 -0700] 101 10.0.0.221, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-10T17_56_21_732Z-debug.log
[10:56:21] INFO: Starting Node-RED...

> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

2019/11/10 10:56:22 [error] 653#653: *1049 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.2:8123"
[10/Nov/2019:10:56:22 -0700] 502 10.0.0.221, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36)
10 Nov 10:56:22 - [info] 

Welcome to Node-RED
===================

10 Nov 10:56:22 - [info] Node-RED version: v1.0.2
10 Nov 10:56:22 - [info] Node.js  version: v10.16.3
10 Nov 10:56:22 - [info] Linux 4.16.0-0.bpo.2-amd64 x64 LE
10 Nov 10:56:23 - [info] Loading palette nodes
2019/11/10 10:56:23 [error] 653#653: *1049 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.2:8123"
[10/Nov/2019:10:56:23 -0700] 502 10.0.0.221, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36)
10 Nov 10:56:24 - [info] Dashboard version 2.17.1 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 4, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python2.7/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
10 Nov 10:56:24 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
10 Nov 10:56:24 - [info] Settings file  : /etc/node-red/config.js
10 Nov 10:56:24 - [info] Context store  : 'default' [module=memory]
10 Nov 10:56:24 - [info] User directory : /config/node-red/
10 Nov 10:56:24 - [warn] Projects disabled : editorTheme.projects.enabled=false
10 Nov 10:56:24 - [info] Flows file     : /config/node-red/flows.json
10 Nov 10:56:24 - [info] Server now running at http://127.0.0.1:46836/
10 Nov 10:56:24 - [info] Starting flows
10 Nov 10:56:25 - [info] Started flows
10 Nov 10:56:25 - [info] [mqtt-broker:Mosquitto MQTT] Connected to broker: mqtt://localhost:1883
10 Nov 10:56:29 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistan
```

**Comment by orcema** [comment]
"cacheFolder" should be an existing folder.
I didn't see the need for the node to create missing folders and if so it would also have to manage privileges about creating folder. Thus at current stage this is out of scope.
