### ISSUE TITLE
castv2-client 

### ISSUE THREAD

**Issue by Paulf007** [orcema/node-red-contrib-google-home-notifier-offline#9]
Does this node use castv2-client?
I am getting the following error
` at fn.ontimeout (/home/farmgeluk/.node-red/node_modules/castv2-client/lib/senders/platform.js:56:26)`
and the only node , that I know of  in my system,  that uses Google is home-notifier-offline.
Else this node is working very well and thank you for all the hard work!

**Comment by orcema** [comment]
yes it uses the node "castv2-client".  It's the first time this error occurs ? I never had an error like this.

**Comment by Paulf007** [comment]
The error happens once or twice a day , here is what I get in syslog

```
Jul 28 03:27:41 farm-geluk-server Node-RED[24871]: Error: Device timeout
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]: 28 Jul 03:27:42 - [red] Uncaught Exception:
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]: 28 Jul 03:27:42 - Error: Device timeout
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]:     at fn.ontimeout (/home/farmgeluk/.node-red/node_modules/castv2-client/lib/senders/platform.js:56:26)
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]:     at Object.onceWrapper (events.js:421:28)
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]:     at fn.emit (events.js:315:20)
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]:     at Timeout.ontimeout [as _onTimeout] (/home/farmgeluk/.node-red/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]:     at listOnTimeout (internal/timers.js:549:17)
Jul 28 03:27:42 farm-geluk-server Node-RED[24871]:     at processTimers (internal/timers.js:492:7)
Jul 28 03:27:42 farm-geluk-server systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Jul 28 03:27:42 farm-geluk-server systemd[1]: nodered.service: Failed with result 'exit-code'.
Jul 28 03:27:42 farm-geluk-server systemd[1]: nodered.service: Service hold-off time over, scheduling restart.
Jul 28 03:27:42 farm-geluk-server systemd[1]: nodered.service: Scheduled restart job, restart counter is at 23.
Jul 28 03:27:42 farm-geluk-server systemd[1]: Stopped Node-RED graphical event wiring tool.
Jul 28 03:27:42 farm-geluk-server systemd[1]: Started Node-RED graphical event wiring tool.

```
and these are the nodes that uses castv2-client

farmgeluk@farm-geluk-server:~/.node-red$ npm list castv2-client
node-red-project@0.0.1 /home/farmgeluk/.node-red
└─┬ node-red-contrib-google-home-notifier-offline@0.1.5
  └─┬ google-home-notifier-offline@1.0.2
    └── castv2-client@1.2.0
 
I notice that there is are two google-home-notifier-offline (1.0.2 & 0.1.5) does this make any difference?

**Comment by Paulf007** [comment]
I uninstalled the node and then reinstalled, I noticed that there is a couple of warnings in the log 
Not sure if this helps ?
```
2020-07-28T03:26:21.555Z Install : node-red-contrib-google-home-notifier-offline 0.1.5

2020-07-28T03:26:22.134Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-google-home-notifier-offline@0.1.5
2020-07-28T03:26:40.736Z [err] npm WARN deprecated
2020-07-28T03:26:40.736Z [err]  chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
2020-07-28T03:26:42.166Z [err] npm 
2020-07-28T03:26:42.166Z [err] WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
2020-07-28T03:26:48.719Z [err] npm
2020-07-28T03:26:48.719Z [err]  WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
2020-07-28T03:26:48.730Z [err] npm WARN
2020-07-28T03:26:48.730Z [err]  deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
2020-07-28T03:27:07.429Z [out] 
2020-07-28T03:27:07.429Z [out] > protobufjs@6.10.1 postinstall /home/farmgeluk/.node-red/node_modules/protobufjs
2020-07-28T03:27:07.429Z [out] > node scripts/postinstall
2020-07-28T03:27:07.429Z [out] 
2020-07-28T03:27:07.860Z [err] npm
2020-07-28T03:27:07.860Z [err]  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
2020-07-28T03:27:07.860Z [err] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-07-28T03:27:07.860Z [err] npm WARN
2020-07-28T03:27:07.860Z [err]  node-red-project@0.0.1 No repository field.
2020-07-28T03:27:07.860Z [err] npm WARN node-red-project@0.0.1 No license field.
2020-07-28T03:27:07.861Z [err] 
2020-07-28T03:27:07.863Z [out] + node-red-contrib-google-home-notifier-offline@0.1.5
2020-07-28T03:27:07.863Z [out] added 178 packages from 175 contributors in 45.212s
2020-07-28T03:27:07.879Z rc=0
```

**Comment by orcema** [comment]
# replaced by [node-red-google-notify](https://flows.nodered.org/node/node-red-google-notify).
